import express from "express";
import AuthMiddleware from "../../../middlewares/auth.middleware.js";
import AdminMiddleware from "../../../middlewares/admin.middleware.js";
import * as AdminRouters from "./Admin/index.js";
import * as AddressRouters from "./Address/index.js";
import * as AuthRouters from "./Auth/index.js";
import * as CartRouters from "./Cart/index.js";
import * as CategoryRouters from "./Category/index.js";
import * as CityRouters from "./City/index.js";
import * as CollectionRouters from "./Collection/index.js";
import * as CountryRouters from "./Country/index.js";
import * as OrderRouters from "./Order/index.js";
import * as OrderStatusRouters from "./OrderStatus/index.js";
import * as OtpRouters from "./OtpVerification/index.js";
import * as PaymentRouters from "./Payment/index.js";
import * as PaymentMethodRouters from "./PaymentMethod/index.js";
import * as PaymentStatusRouters from "./PaymentStatus/index.js";
import * as ProductRouters from "./Product/index.js";
import * as ImageRouters from "./Image/index.js";
import * as ReviewRouters from "./Review/index.js";
import * as RoleRouters from "./Role/index.js";
import * as PermissionRouters from "./Permission/index.js";
import * as SubcategoryRouters from "./Subcategory/index.js";
import * as UserRouters from "./User/index.js";
import * as TokenRouters from "./Token/index.js";
const router = express.Router();
const registerRoutes = (routes, options = {}) => {
  const { auth = false, admin = false } = options;
  Object.entries(routes).forEach(([name, routeModule]) => {
    const middlewares = [];
    if (auth) middlewares.push(AuthMiddleware);
    if (admin) middlewares.push(AdminMiddleware);
    const basePath = `/${name.replace(/_/g, "-")}`;
    router.use(basePath, ...middlewares, routeModule);
  });
};
registerRoutes(AdminRouters, { auth: false });
registerRoutes(AddressRouters, { auth: false });
registerRoutes(AuthRouters);
registerRoutes(CartRouters, { auth: false });
registerRoutes(CategoryRouters, { auth: false });
registerRoutes(CityRouters, { auth: false });
registerRoutes(CollectionRouters, { auth: false });
registerRoutes(CountryRouters, { auth: false });
registerRoutes(OrderRouters, { auth: false });
registerRoutes(OrderStatusRouters, { auth: false });
registerRoutes(OtpRouters);
registerRoutes(PaymentRouters, { auth: false });
registerRoutes(PaymentMethodRouters, { auth: false });
registerRoutes(PaymentStatusRouters, { auth: false });
registerRoutes(ProductRouters, { auth: false });
registerRoutes(ImageRouters, { auth: false });
registerRoutes(ReviewRouters, { auth: false });
registerRoutes(RoleRouters, { auth: false });
registerRoutes(PermissionRouters, { auth: false });
registerRoutes(SubcategoryRouters, { auth: false });
registerRoutes(UserRouters, { auth: false });
registerRoutes(TokenRouters, { auth: false });
export default router;
