import swaggerJsdoc from "swagger-jsdoc";
const options = {
    definition: {
        openapi: "3.0.0",
        info: {
            title: "E-commerce API",
            version: "1.0.0",
        },
        servers: [
            {
                url: "http://localhost:5000/api/v1",
                description: "Development Server",
            },
        ],
        tags: [
            { name: "Addresses" },
            { name: "Admins" },
            { name: "Auth" },
            { name: "Carts" },
            { name: "Categories" },
            { name: "Cities" },
            { name: "Collections" },
            { name: "Countries" },
            { name: "OrderStatuses" },
            { name: "Orders" },
            { name: "PaymentMethods" },
            { name: "PaymentStatuses" },
            { name: "Payments" },
            { name: "Permissions" },
            { name: "Products" },
            { name: "Reviews" },
            { name: "Roles" },
            { name: "Subcategories" },
            { name: "Users" }
        ],
        components: {
            securitySchemes: {
                BearerAuth: {
                    type: "oauth2",
                    flows: {
                        password: {
                            tokenUrl: "http://localhost:5000/api/v1/auth/login",
                            scopes: {},
                        },
                    },
                },
            },
            schemas: {
                Admin: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        FirstName: { type: "string" },
                        LastName: { type: "string" },
                        Email: { type: "string" },
                        UserName: { type: "string" },
                        Phone: { type: "string" },
                        RoleID: { type: "string" },
                        ImageID: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Role: { $ref: "#/components/schemas/Role" },
                        Image: { $ref: "#/components/schemas/Image" },
                    },
                },
                User: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        FirstName: { type: "string" },
                        LastName: { type: "string" },
                        Email: { type: "string" },
                        Phone: { type: "string" },
                        ImageID: { type: "string" },
                        Password: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Image: { $ref: "#/components/schemas/Image" },
                    },
                },
                Category: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        Slug: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Products: { type: "array", items: { $ref: "#/components/schemas/Product" } },
                    },
                },
                Subcategory: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        CategoryID: { type: "string" },
                        Slug: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Category: { $ref: "#/components/schemas/Category" },
                        Products: { type: "array", items: { $ref: "#/components/schemas/Product" } },
                    },
                },
                Collection: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Slug: { type: "string" },
                        Description: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Products: { type: "array", items: { $ref: "#/components/schemas/Product" } },
                    },
                },
                Address: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        UserID: { type: "string" },
                        CityID: { type: "string" },
                        CountryID: { type: "string" },
                        AddressLine1: { type: "string" },
                        AddressLine2: { type: "string" },
                        PostalCode: { type: "string" },
                        IsDefault: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        User: { $ref: "#/components/schemas/User" },
                        City: { $ref: "#/components/schemas/City" },
                        Country: { $ref: "#/components/schemas/Country" },
                    },
                },
                Cart: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        UserID: { type: "string" },
                        TotalPrice: { type: "number" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        User: { $ref: "#/components/schemas/User" },
                        Products: {
                            type: "array",
                            items: {
                                type: "object",
                                properties: {
                                    ProductID: { type: "string" },
                                    Product: { $ref: "#/components/schemas/Product" },
                                    Quantity: { type: "number" },
                                },
                            },
                        },
                    },
                },
                Payment: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        UserID: { type: "string" },
                        Amount: { type: "number" },
                        CurrencySymbolID: { type: "string" },
                        PaymentMethodID: { type: "string" },
                        PaymentStatusID: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        User: { $ref: "#/components/schemas/User" },
                        PaymentMethod: { $ref: "#/components/schemas/PaymentMethod" },
                        PaymentStatus: { $ref: "#/components/schemas/PaymentStatus" },
                    },
                },
                Order: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        UserID: { type: "string" },
                        AddressID: { type: "string" },
                        PaymentID: { type: "string" },
                        OrderStatusID: { type: "string" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        User: { $ref: "#/components/schemas/User" },
                        Address: { $ref: "#/components/schemas/Address" },
                        Payment: { $ref: "#/components/schemas/Payment" },
                        OrderStatus: { $ref: "#/components/schemas/OrderStatus" },
                        Items: {
                            type: "array",
                            items: {
                                type: "object",
                                properties: {
                                    ProductID: { type: "string" },
                                    Product: { $ref: "#/components/schemas/Product" },
                                    Quantity: { type: "number" },
                                },
                            },
                        },
                    },
                },
                Product: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        Price: { type: "number" },
                        Stock: { type: "number" },
                        CategoryIDs: { type: "array", items: { type: "string" } },
                        CollectionIDs: { type: "array", items: { type: "string" } },
                        SubcategoryIDs: { type: "array", items: { type: "string" } },
                        ImageIDs: { type: "array", items: { type: "string" } },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Subcategories: { type: "array", items: { $ref: "#/components/schemas/Subcategory" } },
                        Categories: { type: "array", items: { $ref: "#/components/schemas/Category" } },
                        Collections: { type: "array", items: { $ref: "#/components/schemas/Collection" } },
                        Images: { type: "array", items: { $ref: "#/components/schemas/Image" } },
                    },
                },
                City: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        CountryID: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Country: { $ref: "#/components/schemas/Country" },
                    },
                },
                Country: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        CurrencySymbolID: { type: "string" },
                        Slug: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Cities: { type: "array", items: { $ref: "#/components/schemas/City" } },
                    },
                },
                Role: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Permissions: {
                            type: "array",
                            items: { $ref: "#/components/schemas/Permission" },
                        },
                    },
                },
                Permission: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        IsActivated: { type: "boolean" },
                        RoleID: { type: "string" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        Role: { $ref: "#/components/schemas/Role" },
                    },
                },
                Review: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        UserID: { type: "string" },
                        ProductID: { type: "string" },
                        Rating: { type: "number" },
                        Comment: { type: "string" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                        User: { $ref: "#/components/schemas/User" },
                        Product: { $ref: "#/components/schemas/Product" },
                    },
                },
                Image: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        path: { type: "string" },
                        filename: { type: "string" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                    },
                },
                OrderStatus: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                    },
                },
                PaymentStatus: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                    },
                },
                PaymentMethod: {
                    type: "object",
                    properties: {
                        _id: { type: "string" },
                        Name: { type: "string" },
                        Description: { type: "string" },
                        IsActivated: { type: "boolean" },
                        IsDeleted: { type: "boolean" },
                        CreatedBy: { type: "string" },
                        CreatedDate: { type: "string", format: "date-time" },
                        UpdatedBy: { type: "string" },
                        UpdatedDate: { type: "string", format: "date-time" },
                    },
                },
                Error: {
                    type: "object",
                    properties: {
                        success: { type: "boolean", example: false },
                        message: { type: "string", example: "Error message" },
                    },
                },
            },
            parameters: {
                PageParam: {
                    in: "query",
                    name: "page",
                    schema: { type: "integer", minimum: 1, default: 1 },
                    required: false,
                    description: "Page number for pagination",
                    example: 1,
                },
                LimitParam: {
                    in: "query",
                    name: "limit",
                    schema: {
                        type: "integer",
                        minimum: 1,
                        maximum: 100,
                        default: 5,
                        enum: [5, 10, 15, 20],
                    },
                    required: false,
                    description: "Number of results per page",
                    example: 5,
                },
                SortParam: {
                    in: "query",
                    name: "sort",
                    schema: {
                        type: "string",
                        enum: [
                            "newest",
                            "oldest",
                            "a_z",
                            "z_a",
                            "price_asc",
                            "price_desc",
                            "amount_asc",
                            "amount_desc",
                        ],
                        default: "newest",
                    },
                    required: false,
                    description: "Sort order for the results",
                },
            },
        },
        security: [
            {
                BearerAuth: [],
            },
        ],
    },
    apis: ["./modules/presentation/routes/**/*.js"],
};
const swaggerSpec = swaggerJsdoc(options);
export default swaggerSpec;
