import express from "express";
import CreateSubcategory from "./routers/CreateSubcategory.routes.js";
import DeleteSubcategory from "./routers/DeleteSubcategory.routes.js";
import GetAllSubcategoriesByCategoryID from "./routers/GetAllSubcategoriesByCategoryID.routes.js";
import GetAllSubcategories from "./routers/GetAllSubcategories.routes.js";
import GetSubcategoryByID from "./routers/GetSubcategoryByID.routes.js";
import GetSubcategoryBySlug from "./routers/GetSubcategoryBySlug.routes.js";
import UpdateSubcategory from "./routers/UpdateSubcategory.routes.js";
import ActiveSubcategoryByID from "./routers/ActiveSubcategoryByID.routes.js";
const subcategory = express.Router();
subcategory.use("/", CreateSubcategory);
subcategory.use("/", DeleteSubcategory);
subcategory.use("/", GetSubcategoryByID);
subcategory.use("/slug", GetSubcategoryBySlug);
subcategory.use("/", UpdateSubcategory);
subcategory.use("/active", ActiveSubcategoryByID);
const subcategories = express.Router();
subcategories.use("/", GetAllSubcategories);
subcategories.use("/category", GetAllSubcategoriesByCategoryID);
export { subcategory, subcategories };
